"""empty message

Revision ID: 24fec12ae850
Revises: 63dae36ea6dc
Create Date: 2023-12-10 18:19:02.886237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24fec12ae850'
down_revision = '63dae36ea6dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project', sa.String(length=140), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiment', schema=None) as batch_op:
        batch_op.drop_column('project')

    # ### end Alembic commands ###
